GLOBAL.setfenv(1, GLOBAL)

-- 住房相关常量
WORLD_TILES.INTERIOR = WORLD_TILES.INVALID - 1
INVERTED_WORLD_TILES[WORLD_TILES.INTERIOR] = "INTERIOR"

-- 室内间距常量
INTERIOR_SPACEING = 4

-- 物理碰撞常量
COLLISION = COLLISION or {}
COLLISION.VOID_LIMITS = 2
COLLISION.GROUND = COLLISION.GROUND or 64
COLLISION.ITEMS = COLLISION.ITEMS or 512
